
/* SavingsTransactions */
CREATE TABLE APP.SAVINGS_TRANSACTIONS (
ID INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), 
ACCOUNT_KEY INT NOT NULL REFERENCES ACCOUNTS, 
CATEGORY VARCHAR(10) ,-- Deposit / Withdrawal
DESCRIPTION VARCHAR(50),
AMOUNT NUMERIC(19, 4)
);