//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWBA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.BillPays = new HashSet<BillPay>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int AccountNumber { get; set; }
        public string AccountType { get; set; }
        public int CustomerID { get; set; }
        public System.DateTime ModifyDate { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<BillPay> BillPays { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
