//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWBA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionDestination
    {
        public int TranscationID { get; set; }
        public int DestAccount { get; set; }
    
        public virtual Transaction Transaction { get; set; }
    }
}
